version: 2
updates:
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    # Check the nuget for updates every day (weekdays)
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "IDT.MT.Remittance.*"