name: Create Repository Release
on:
  workflow_dispatch:
    inputs:
      major:
        description: "(OPTIONAL) Major version to override next major version (number)"
        type: string
      minor:
        description: "(OPTIONAL) Minor version to override next minor version (number)"
        type: string
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          token: ${{ format('{0}{1}', secrets.GHTP1, secrets.GHTP2) }}
      - name: Check out action code
        uses: actions/checkout@v3
        with:
          repository: coretech/boss-mr-github-actions-lib
          token: ${{ format('{0}{1}', secrets.GHTP1, secrets.GHTP2) }}
          path: github-actions
      - name: Resolve next release version
        id: release_version
        uses: ./github-actions/.github/actions/resolve-release-version
        with:
          repository: ${{ github.repository }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          major: ${{ inputs.major }}
          minor: ${{ inputs.minor }}
      - name: Create release branch
        run: git checkout -b release.${{ steps.release_version.outputs.nextTag }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Push new branch
        run: git push origin release.${{ steps.release_version.outputs.nextTag }}
